apiVersion: apps/v1
kind: Deployment
metadata:
  name: myclassifier-deployment
  namespace: myclassifier-namespace
spec:
  selector:
    matchLabels:
      app: myclassifier
  replicas: 2
  template:
    metadata:
      labels:
        app: myclassifier
    spec:
      containers:
      - name: myclassifier-server
        image: myclassifier:0.0.1
        imagePullPolicy: Never
        command: ["uvicorn", "app_classifier.main:app"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8000
        env:
          - name: "JWT_SECRET"
            value: "My_secret"
          - name: "BASE_ENCODING_ALGORITHM"
            value: "HS256"
          - name: "USERNAME_1"
            value: "client_user"
          - name: "PASSWORD_1"
            value: "tryClassifier"
          - name: "MODEL_PATH"
            value: "models/resnet101_scripted.pt"
          - name: "MODEL_PATH_EAGER"
            value: "models/resnet101.pth"
          - name: "S3_PATH"
            value: "http://s3-ap-northeast-1.amazonaws.com/myclassifier/"
          - name: "VERSION"
            "value": 0.0.1