apiVersion: v1
kind: Service
metadata:
  name: myclassifier-service
  namespace: myclassifier-namespace
spec:
  type: LoadBalancer
  selector:
    app: myclassifier
  ports:
  - port: 8000
    targetPort: 8000